"""recommendation_item_material_tag

Revision ID: 15b79f06a12e
Revises: 13ea5cd95299
Create Date: 2026-10-01 00:30:00.000000

Adds RecommendationItem.material_tag — a short stone/material display tag
for PRODUCT items, generated by app/services/ai_recommendation.py. Purely
additive, nullable, no data migration needed.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b79f06a12e'
down_revision: Union[str, Sequence[str], None] = '13ea5cd95299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('recommendation_items', sa.Column('material_tag', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('recommendation_items', 'material_tag')
