"""check_in_session_title_subtitle_zh

Revision ID: 8a82d868a7c5
Revises: f21d9c8e7012
Create Date: 2026-09-30 08:52:10.582801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a82d868a7c5'
down_revision: Union[str, Sequence[str], None] = 'f21d9c8e7012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_in_sessions', sa.Column('title_zh', sa.String(), nullable=True))
    op.add_column('check_in_sessions', sa.Column('subtitle_zh', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_in_sessions', 'subtitle_zh')
    op.drop_column('check_in_sessions', 'title_zh')
    # ### end Alembic commands ###
