"""initial schema

Revision ID: 9a3e05e4b10a
Revises: 
Create Date: 2026-09-22 12:00:50.397377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a3e05e4b10a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in_question_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('blueprint_version', sa.String(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_question_sets_date'), 'check_in_question_sets', ['date'], unique=True)
    op.create_table('inner_reading_question_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('blueprint_version', sa.String(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inner_reading_question_sets_ordinal'), 'inner_reading_question_sets', ['ordinal'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('gid', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('preferred_language', sa.String(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('core_personality_last_recalibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gid')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('check_in_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('blueprint_version', sa.String(), nullable=False),
    sa.Column('private_note', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_sessions_user_id'), 'check_in_sessions', ['user_id'], unique=False)
    op.create_table('core_personalities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('archetype', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('thinking', sa.SmallInteger(), nullable=False),
    sa.Column('emotional_sensitivity', sa.SmallInteger(), nullable=False),
    sa.Column('adaptability', sa.SmallInteger(), nullable=False),
    sa.Column('willpower', sa.SmallInteger(), nullable=False),
    sa.Column('overall_explanation', sa.String(), nullable=False),
    sa.Column('pillar_explanations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assessment_version', sa.String(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recalibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_personalities_user_id'), 'core_personalities', ['user_id'], unique=False)
    op.create_table('garden_progress',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('stage', sa.SmallInteger(), nullable=False),
    sa.Column('actions_this_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('inner_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('blueprint_version', sa.String(), nullable=False),
    sa.Column('emotional_energy', sa.SmallInteger(), nullable=True),
    sa.Column('mental_clarity', sa.SmallInteger(), nullable=True),
    sa.Column('inner_pressure', sa.SmallInteger(), nullable=True),
    sa.Column('grounding', sa.SmallInteger(), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=True),
    sa.Column('narrative', sa.String(), nullable=True),
    sa.Column('insight', sa.String(), nullable=True),
    sa.Column('reflection_question', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inner_readings_user_id'), 'inner_readings', ['user_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('mood', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_created_at'), 'journal_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('billing_cycle', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_free_reading_consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_key', sa.String(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'badge_key')
    )
    op.create_table('user_quests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quest', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'quest', 'date', name='uq_user_quest_per_day')
    )
    op.create_index(op.f('ix_user_quests_user_id'), 'user_quests', ['user_id'], unique=False)
    op.create_table('user_rewards',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reward_key', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'reward_key')
    )
    op.create_table('user_streaks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('best', sa.Integer(), nullable=False),
    sa.Column('last_reflection_date', sa.Date(), nullable=True),
    sa.Column('milestones_awarded', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('xp_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('source_action', sa.String(), nullable=False),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_key', name='uq_xp_transaction_dedupe')
    )
    op.create_index(op.f('ix_xp_transactions_user_id'), 'xp_transactions', ['user_id'], unique=False)
    op.create_table('check_in_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('check_in_session_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('answer_value', sa.SmallInteger(), nullable=False),
    sa.Column('normalized_value', sa.SmallInteger(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['check_in_session_id'], ['check_in_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_answers_check_in_session_id'), 'check_in_answers', ['check_in_session_id'], unique=False)
    op.create_table('inner_reading_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inner_reading_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('answer_value', sa.SmallInteger(), nullable=False),
    sa.Column('normalized_value', sa.SmallInteger(), nullable=False),
    sa.Column('order_index', sa.SmallInteger(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inner_reading_id'], ['inner_readings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inner_reading_answers_inner_reading_id'), 'inner_reading_answers', ['inner_reading_id'], unique=False)
    op.create_table('inner_state_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('check_in_session_id', sa.UUID(), nullable=True),
    sa.Column('inner_reading_id', sa.UUID(), nullable=True),
    sa.Column('emotional_energy', sa.SmallInteger(), nullable=False),
    sa.Column('mental_clarity', sa.SmallInteger(), nullable=False),
    sa.Column('inner_pressure', sa.SmallInteger(), nullable=False),
    sa.Column('grounding', sa.SmallInteger(), nullable=False),
    sa.Column('balance', sa.SmallInteger(), nullable=False),
    sa.Column('current_focus', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(check_in_session_id IS NOT NULL)::int + (inner_reading_id IS NOT NULL)::int = 1', name='ck_inner_state_snapshot_single_source'),
    sa.ForeignKeyConstraint(['check_in_session_id'], ['check_in_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inner_reading_id'], ['inner_readings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inner_state_snapshots_created_at'), 'inner_state_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_inner_state_snapshots_user_id'), 'inner_state_snapshots', ['user_id'], unique=False)
    op.create_table('recommendation_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('state_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('core_personality_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('trigger_check_in_session_id', sa.UUID(), nullable=True),
    sa.Column('trigger_inner_reading_id', sa.UUID(), nullable=True),
    sa.Column('current_focus', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('colour_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(trigger_check_in_session_id IS NOT NULL)::int + (trigger_inner_reading_id IS NOT NULL)::int = 1', name='ck_recommendation_single_trigger'),
    sa.ForeignKeyConstraint(['core_personality_id'], ['core_personalities.id'], ),
    sa.ForeignKeyConstraint(['state_snapshot_id'], ['inner_state_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_check_in_session_id'], ['check_in_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_inner_reading_id'], ['inner_readings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_profiles_generated_at'), 'recommendation_profiles', ['generated_at'], unique=False)
    op.create_index(op.f('ix_recommendation_profiles_user_id'), 'recommendation_profiles', ['user_id'], unique=False)
    op.create_table('recommendation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_profile_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('destination_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_profile_id'], ['recommendation_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_items_recommendation_profile_id'), 'recommendation_items', ['recommendation_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_items_recommendation_profile_id'), table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index(op.f('ix_recommendation_profiles_user_id'), table_name='recommendation_profiles')
    op.drop_index(op.f('ix_recommendation_profiles_generated_at'), table_name='recommendation_profiles')
    op.drop_table('recommendation_profiles')
    op.drop_index(op.f('ix_inner_state_snapshots_user_id'), table_name='inner_state_snapshots')
    op.drop_index(op.f('ix_inner_state_snapshots_created_at'), table_name='inner_state_snapshots')
    op.drop_table('inner_state_snapshots')
    op.drop_index(op.f('ix_inner_reading_answers_inner_reading_id'), table_name='inner_reading_answers')
    op.drop_table('inner_reading_answers')
    op.drop_index(op.f('ix_check_in_answers_check_in_session_id'), table_name='check_in_answers')
    op.drop_table('check_in_answers')
    op.drop_index(op.f('ix_xp_transactions_user_id'), table_name='xp_transactions')
    op.drop_table('xp_transactions')
    op.drop_table('user_streaks')
    op.drop_table('user_rewards')
    op.drop_index(op.f('ix_user_quests_user_id'), table_name='user_quests')
    op.drop_table('user_quests')
    op.drop_table('user_badges')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_created_at'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_inner_readings_user_id'), table_name='inner_readings')
    op.drop_table('inner_readings')
    op.drop_table('garden_progress')
    op.drop_index(op.f('ix_core_personalities_user_id'), table_name='core_personalities')
    op.drop_table('core_personalities')
    op.drop_index(op.f('ix_check_in_sessions_user_id'), table_name='check_in_sessions')
    op.drop_table('check_in_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_inner_reading_question_sets_ordinal'), table_name='inner_reading_question_sets')
    op.drop_table('inner_reading_question_sets')
    op.drop_index(op.f('ix_check_in_question_sets_date'), table_name='check_in_question_sets')
    op.drop_table('check_in_question_sets')
    # ### end Alembic commands ###
