"""subscription_payments

Revision ID: d30cd7e45698
Revises: d9b5ce16447b
Create Date: 2026-09-25 07:35:57.617681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd30cd7e45698'
down_revision: Union[str, Sequence[str], None] = 'd9b5ce16447b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('billing_cycle', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('xendit_invoice_id', sa.String(), nullable=True),
    sa.Column('reference_no', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('invoice_url', sa.String(), nullable=True),
    sa.Column('provider_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_no')
    )
    op.create_index(op.f('ix_subscription_payments_user_id'), 'subscription_payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_xendit_invoice_id'), 'subscription_payments', ['xendit_invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_payments_xendit_invoice_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_user_id'), table_name='subscription_payments')
    op.drop_table('subscription_payments')
    # ### end Alembic commands ###
