"""checkin_title_subtitle_and_unlocked_content

Revision ID: d3f19b4ea0f9
Revises: d30cd7e45698
Create Date: 2026-09-26 18:10:52.258286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f19b4ea0f9'
down_revision: Union[str, Sequence[str], None] = 'd30cd7e45698'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_unlocked_content',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category', 'item_id')
    )
    op.add_column('check_in_sessions', sa.Column('title', sa.String(), nullable=True))
    op.add_column('check_in_sessions', sa.Column('subtitle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_in_sessions', 'subtitle')
    op.drop_column('check_in_sessions', 'title')
    op.drop_table('user_unlocked_content')
    # ### end Alembic commands ###
